import { auth, db } from './firebase-config.js';
import { onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js';
import { addDoc, collection, deleteDoc, doc, getDoc, getDocs, orderBy, query, serverTimestamp, updateDoc } from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js';

const $ = (selector, root = document) => root.querySelector(selector);
const esc = value => String(value ?? '').replace(/[&<'"]/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[char]));
let profile = null;
let brigades = [];
const today = () => new Date().toISOString().slice(0, 10);
const formatDate = value => value ? new Date(`${value}T12:00:00`).toLocaleDateString('es-CO', { day:'numeric', month:'long', year:'numeric' }) : 'Sin fecha';
function notify(message) { const toast = $('#toast'); if (!toast) return; toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2600); }

async function loadBrigades() { const snapshot = await getDocs(query(collection(db, 'brigades'), orderBy('date', 'asc'))); brigades = snapshot.docs.map(item => ({ id: item.id, ...item.data() })); }
function render() {
  const app = $('#app'); if (!app || location.hash !== '#/brigadas') return;
  if (!profile || profile.role !== 'admin') { app.innerHTML = '<section class="page"><div class="empty"><div>🔒</div><h2>Acceso de coordinación</h2><p>La creación y publicación de brigadas está disponible solo para administradores SIVE.</p></div></section>'; return; }
  app.innerHTML = `<section class="page brigades-admin"><header class="brigades-hero"><div><p class="eyebrow">COORDINACIÓN SIVE</p><h1>Brigadas y actividades</h1><p>Crea, publica y administra las jornadas que se mostrarán automáticamente en el sitio público.</p></div><div><strong>${brigades.filter(item => item.status === 'Activa').length}</strong><span>publicadas</span></div></header><section class="form-card"><div class="section-title"><h2>Nueva brigada</h2><p>Al guardar con estado “Activa” aparecerá en la inscripción pública.</p></div><form id="brigadeAdminForm" class="fields"><div class="field full"><label class="required">Nombre de la brigada</label><input name="name" required placeholder="Ej. Jornada de salud comunitaria"></div><div class="field"><label class="required">Fecha</label><input name="date" type="date" required value="${today()}"></div><div class="field"><label class="required">Lugar</label><input name="place" required placeholder="Municipio, barrio o sede"></div><div class="field"><label>Horario</label><input name="schedule" placeholder="Ej. 08:00 - 12:00"></div><div class="field"><label>Cupos</label><input name="capacity" type="number" min="1" placeholder="Ej. 30"></div><div class="field"><label class="required">Estado</label><select name="status" required><option value="Borrador">Borrador</option><option value="Activa">Activa</option><option value="Finalizada">Finalizada</option></select></div><div class="form-actions full"><button class="primary" type="submit">Guardar brigada</button></div></form></section><section class="brigade-management"><h2>Brigadas creadas</h2><div class="brigade-management-list">${brigades.map(item => `<article class="brigade-management-card"><div><span class="badge">${esc(item.status || 'Borrador')}</span><h3>${esc(item.name)}</h3><p>${esc(formatDate(item.date))} · ${esc(item.place)}</p><small>${esc(item.schedule || 'Horario por definir')} · ${esc(item.capacity || 'Sin límite')} cupos</small></div><div class="brigade-management-actions"><button class="secondary" data-status="${esc(item.id)}" type="button">${item.status === 'Activa' ? 'Ocultar' : 'Publicar'}</button><button class="danger" data-delete="${esc(item.id)}" type="button">Eliminar</button></div></article>`).join('') || '<div class="empty"><div>⌁</div><h2>No hay brigadas creadas</h2><p>Crea la primera jornada desde este formulario.</p></div>'}</div></section></section>`;
  $('#brigadeAdminForm').onsubmit = saveBrigade;
  document.querySelectorAll('[data-status]').forEach(button => button.onclick = () => toggleStatus(button.dataset.status));
  document.querySelectorAll('[data-delete]').forEach(button => button.onclick = () => removeBrigade(button.dataset.delete));
}
async function saveBrigade(event) { event.preventDefault(); const form = event.currentTarget; if (!form.reportValidity()) return; const values = Object.fromEntries(new FormData(form)), button = $('button[type="submit"]', form); button.disabled = true; try { await addDoc(collection(db, 'brigades'), { organizationId:'sive', name:values.name.trim(), date:values.date, place:values.place.trim(), schedule:values.schedule.trim(), capacity:Number(values.capacity) || 0, status:values.status, createdBy:auth.currentUser.uid, createdByName:profile.name || auth.currentUser.email, createdAt:serverTimestamp(), updatedAt:serverTimestamp() }); await loadBrigades(); render(); notify('Brigada guardada correctamente.'); } catch (error) { console.error(error); button.disabled = false; notify('No fue posible guardar la brigada. Verifica las reglas de Firebase.'); } }
async function toggleStatus(id) { const item = brigades.find(value => value.id === id); if (!item) return; try { await updateDoc(doc(db,'brigades',id), { status:item.status === 'Activa' ? 'Borrador' : 'Activa', updatedAt:serverTimestamp() }); await loadBrigades(); render(); notify(item.status === 'Activa' ? 'Brigada ocultada.' : 'Brigada publicada.'); } catch (error) { console.error(error); notify('No fue posible actualizar la brigada.'); } }
async function removeBrigade(id) { if (!confirm('¿Eliminar esta brigada? Esta acción no elimina autorizaciones ya generadas.')) return; try { await deleteDoc(doc(db,'brigades',id)); await loadBrigades(); render(); notify('Brigada eliminada.'); } catch (error) { console.error(error); notify('No fue posible eliminar la brigada.'); } }
function maybeRender() { if (location.hash === '#/brigadas' && auth.currentUser) loadBrigades().then(render).catch(error => { console.error(error); notify('No fue posible cargar las brigadas.'); }); }
onAuthStateChanged(auth, async user => { if (!user) { profile = null; return; } const snapshot = await getDoc(doc(db,'professionals',user.uid)); profile = snapshot.exists() ? snapshot.data() : null; maybeRender(); });
addEventListener('hashchange', maybeRender);
