const NAVY='0B3558',TEAL='4C8C84',PALE='EAF4F2',LINE='B8CFCA',WHITE='FFFFFF',TEXT='243B3A';
const value=v=>v===undefined||v===null||v===''?'No registrado':String(v);
const formatDate=v=>{if(!v)return'No registrada';const [y,m,d]=v.split('-');return y&&m&&d?`${d}/${m}/${y}`:v};

function ageText(birth,visit){if(!birth||!visit)return'No registrada';const a=new Date(`${birth}T12:00:00`),b=new Date(`${visit}T12:00:00`);let years=b.getFullYear()-a.getFullYear(),months=b.getMonth()-a.getMonth();if(b.getDate()<a.getDate())months--;if(months<0){years--;months+=12}return `${years} años, ${months} meses`}
function ageMonths(birth,visit){if(!birth||!visit)return null;const a=new Date(`${birth}T12:00:00`),b=new Date(`${visit}T12:00:00`);let months=(b.getFullYear()-a.getFullYear())*12+b.getMonth()-a.getMonth();if(b.getDate()<a.getDate())months--;return months}

export function buildClinicalDocument(D,data,who,logoBytes){
 const {Document,Packer,Paragraph,TextRun,Table,TableRow,TableCell,WidthType,AlignmentType,VerticalAlign,ImageRun,Header,Footer,PageNumber,BorderStyle,ShadingType}=D;
 const adolescent=data.cycle==='adolescent',early=data.cycle==='early',months=ageMonths(data.birthDate,data.visitDate),earlyStage=months!==null&&months<12?'LACTANTE MENOR 1 A 11 MESES':months!==null&&months<24?'LACTANTE MAYOR 12 A 23 MESES':'PREESCOLAR 2 A 5 AÑOS',documentTitle=early?`HISTORIA CLÍNICA - PRIMERA INFANCIA · ${earlyStage}`:adolescent?'HISTORIA CLÍNICA - ADOLESCENCIA 12 A 17 AÑOS':'HISTORIA CLÍNICA - INFANCIA ESCOLAR 6 A 11 AÑOS',border={style:BorderStyle.SINGLE,size:4,color:LINE},borders={top:border,bottom:border,left:border,right:border};
 const text=(s,bold=false,color=TEXT,size=18)=>new TextRun({text:value(s),bold,color,size,font:'Arial'});
 const p=(s,opts={})=>new Paragraph({children:[text(s,opts.bold,opts.color||TEXT,opts.size||18)],spacing:{after:opts.after??40},alignment:opts.align||AlignmentType.LEFT});
 const cell=(children,width,shade)=>new TableCell({children:Array.isArray(children)?children:[children],width:{size:width,type:WidthType.DXA},verticalAlign:VerticalAlign.CENTER,shading:shade?{fill:shade,type:ShadingType.CLEAR}:undefined,borders,margins:{top:90,bottom:90,left:120,right:120}});
 const kvRows=items=>items.map(([a,b,c,d])=>new TableRow({children:[cell(p(a,{bold:true,color:NAVY}),1900,PALE),cell(p(b),2780),cell(p(c,{bold:true,color:NAVY}),1900,PALE),cell(p(d),2780)]}));
 const kvTable=items=>new Table({rows:kvRows(items),width:{size:9360,type:WidthType.DXA},columnWidths:[1900,2780,1900,2780],layout:'fixed'});
 const sectionTitle=title=>new Paragraph({children:[text(title,true,WHITE,20)],shading:{fill:NAVY,type:ShadingType.CLEAR},spacing:{before:180,after:100},indent:{left:120},keepNext:true});
 const narrative=(label,content)=>new Paragraph({children:[text(`${label}: `,true,NAVY),text(value(content))],spacing:{after:90},keepLines:true});
 const headerTable=new Table({width:{size:9360,type:WidthType.DXA},columnWidths:[1500,6360,1500],layout:'fixed',rows:[new TableRow({children:[new TableCell({children:[new Paragraph({children:logoBytes?[new ImageRun({data:logoBytes,transformation:{width:72,height:72},type:'jpg',altText:{title:'Logo SIVE',description:'Salud Integral Vocacional Estudiantil',name:'Logo SIVE'}})]:[]})],width:{size:1500,type:WidthType.DXA},borders:{top:{style:BorderStyle.NONE},bottom:{style:BorderStyle.NONE},left:{style:BorderStyle.NONE},right:{style:BorderStyle.NONE}}}),new TableCell({children:[p('SIVE',{bold:true,color:NAVY,size:30,align:AlignmentType.CENTER,after:10}),p('SALUD INTEGRAL VOCACIONAL ESTUDIANTIL',{bold:true,color:TEAL,size:15,align:AlignmentType.CENTER})],width:{size:6360,type:WidthType.DXA},verticalAlign:VerticalAlign.CENTER,borders:{top:{style:BorderStyle.NONE},bottom:{style:BorderStyle.NONE},left:{style:BorderStyle.NONE},right:{style:BorderStyle.NONE}}}),new TableCell({children:[p('Historia clínica',{bold:true,color:NAVY,size:15,align:AlignmentType.CENTER})],width:{size:1500,type:WidthType.DXA},verticalAlign:VerticalAlign.CENTER,borders:{top:{style:BorderStyle.NONE},bottom:{style:BorderStyle.NONE},left:{style:BorderStyle.NONE},right:{style:BorderStyle.NONE}}})]})]});
 const results=who?.results||[];
 const resultRows=[new TableRow({tableHeader:true,children:[cell(p('Indicador',{bold:true,color:WHITE}),3300,NAVY),cell(p('Z-score',{bold:true,color:WHITE,align:AlignmentType.CENTER}),1300,NAVY),cell(p('Percentil',{bold:true,color:WHITE,align:AlignmentType.CENTER}),1300,NAVY),cell(p('Clasificación',{bold:true,color:WHITE}),3460,NAVY)]}),...results.map(r=>new TableRow({children:[cell(p(r.label),3300),cell(p(r.z.toFixed(2),{align:AlignmentType.CENTER}),1300),cell(p(r.percentile.toFixed(1),{align:AlignmentType.CENTER}),1300),cell(p(r.flag?'Valor implausible: verificar medición':r.classification),3460,r.flag?'FDE8E8':undefined)]}))];
 const children=[
  p(documentTitle,{bold:true,color:NAVY,size:25,align:AlignmentType.CENTER,after:40}),
  p(`Fecha de valoración: ${formatDate(data.visitDate)}`,{color:TEAL,size:17,align:AlignmentType.CENTER,after:150}),
  sectionTitle('IDENTIFICACIÓN DEL MENOR'),kvTable([
   ['Nombre completo',data.name,early?'Número del registro civil':'Tarjeta de identidad (T.I.)',data.civilRegistry],
   ['Fecha de nacimiento',formatDate(data.birthDate),'Edad',ageText(data.birthDate,data.visitDate)],
   ['Sexo',data.sex,'Teléfono',data.phone],
   ['Acudiente',data.guardianName,'Documento del acudiente',data.guardianDocument],
   ['Dirección',data.address,'Fecha de valoración',formatDate(data.visitDate)]
  ]),
  sectionTitle('MOTIVO DE CONSULTA'),narrative('Motivo',data.consultationReason),
  sectionTitle('VACUNACIÓN'),kvTable([
   ['Carné completo',data.vaccinationComplete,'Vacunas pendientes',data.missingVaccines],
   ['Última vacuna',data.lastVaccineName,'Fecha',formatDate(data.lastVaccineDate)]
  ]),
  sectionTitle('ANTECEDENTES'),narrative('Patológicos',data.pathological),narrative('Familiares',data.family),narrative('Quirúrgicos',data.surgical),narrative('Traumatológicos',data.trauma),narrative('Farmacológicos',data.pharmacological),narrative('Alergias',data.allergies),narrative('Transfusiones',data.transfusions),narrative('Tipo de sangre',data.bloodType),
  sectionTitle('ALIMENTACIÓN'),kvTable([
   ['Desayuno',data.breakfast,'Media mañana / tarde',data.morningSnack],
   ['Almuerzo',data.lunch,'Cena',data.dinner]
  ]),
  sectionTitle('EXAMEN FÍSICO'),kvTable(early?[
   ['Frecuencia cardíaca',`${value(data.heartRate)} lpm`,'Frecuencia respiratoria',`${value(data.respiratoryRate)} rpm`],
   ['Saturación de oxígeno',`${value(data.oxygenSaturation)} %`,'Temperatura',`${value(data.temperature)} °C`],
   ['Peso',`${value(data.weight)} kg`,'Longitud / talla',`${value(data.height)} cm`],
   ['Posición de medición',data.measurementPosition,'Perímetro cefálico',`${value(data.headCircumference)} cm`],
   ['Perímetro braquial',`${value(data.armCircumference)} cm`,'Perímetro torácico',`${value(data.chestCircumference)} cm`],
   ['Perímetro abdominal',`${value(data.abdominalCircumference)} cm`,'Edema bilateral',data.oedema]
  ]:[
   ['Frecuencia cardíaca',`${value(data.heartRate)} lpm`,'Frecuencia respiratoria',`${value(data.respiratoryRate)} rpm`],
   ['Saturación de oxígeno',`${value(data.oxygenSaturation)} %`,'Temperatura',`${value(data.temperature)} °C`],
   ['Peso',`${value(data.weight)} kg`,'Talla',`${value(data.height)} cm`],
   ['Perímetro braquial',`${value(data.armCircumference)} cm`,'IMC',who?.bmi?`${who.bmi.toFixed(2)} kg/m²`:value(data.bmi)],
   ['Clasificación de Tanner',data.tanner,'Edema bilateral',data.oedema]
  ]),narrative('Hallazgos positivos',data.physicalFindings),
  sectionTitle('VALORACIÓN NUTRICIONAL OMS'),new Table({rows:resultRows,width:{size:9360,type:WidthType.DXA},columnWidths:[3300,1300,1300,3460],layout:'fixed'}),
  p(who?.standard||'Referencia OMS 2007 para escolares y adolescentes.',{color:TEAL,size:16,after:80}),
  sectionTitle('PROMOCIÓN Y PREVENCIÓN'),kvTable([
   ['Última desparasitación',data.lastDeworming,'Último control de crecimiento',formatDate(data.lastGrowthControl)],
   ...(early?[['Vitamina A y hierro',data.vitaminAIron,'Etapa de primera infancia',earlyStage]]:[])
  ]),
  ...(adolescent?[sectionTitle('SALUD SEXUAL Y MENSTRUAL'),kvTable([
   ['Inicio de relaciones sexuales',data.sexualActivity,'Tamizaje para ITS/ETS',data.stiScreening],
   ['Menarquia',data.sex==='Femenino'?data.menarche:'No aplica','Fecha de última menstruación',data.sex==='Femenino'&&data.menarche==='Sí'?formatDate(data.lastMenstrualPeriod):'No aplica']
  ]),narrative('Observaciones confidenciales',data.stiNotes)]:[]),
  sectionTitle('RECOMENDACIONES GENERALES'),
  p(adolescent?'Se promueven hábitos de higiene personal y cuidado bucal, salud mental, prevención de accidentes y violencias, alimentación equilibrada, sueño adecuado, actividad física regular y uso responsable de pantallas. Se recomienda mantener el esquema de vacunación completo y asistir a los controles de salud establecidos para la adolescencia.':early?(months!==null&&months<12?'Se orienta sobre lactancia materna, alimentación acorde con la edad, sueño seguro boca arriba, prevención de muerte súbita, baño y cuidado de la piel, cambio de pañal, estimulación temprana, vínculo afectivo y prevención de accidentes.':'Se orienta sobre alimentación natural y variada, continuidad de la lactancia materna hasta los dos años o más cuando sea posible, higiene oral desde la erupción dental, rutinas de sueño, juego, lectura, interacción verbal, actividad física, límites protectores y prevención de accidentes.'):'Se brinda educación sobre prácticas de crianza protectoras y basadas en derechos, prevención de violencias, fortalecimiento de la red de apoyo familiar, alimentación equilibrada, higiene personal y oral, sueño adecuado, actividad física, juego, aprendizaje y prevención de accidentes. Se recomienda asistir a los controles de crecimiento y desarrollo, cumplir las citas de vacunación y mantener un entorno familiar seguro y de apoyo.'),
  ...(adolescent?[sectionTitle('ALIMENTACIÓN Y ACTIVIDAD FÍSICA'),p('Consumir diariamente alimentos variados: frutas, verduras, leguminosas, cereales integrales, lácteos, carnes magras, pescado o huevo. Evitar bebidas azucaradas, exceso de sal y productos ultraprocesados. Realizar actividad física regular acorde con la edad y condición de salud, combinando actividad aeróbica y fortalecimiento muscular.')]:[]),
  ...(adolescent?[sectionTitle('DERECHOS SEXUALES Y REPRODUCTIVOS'),p('Se brinda información clara, científica, confidencial y apropiada para la edad sobre integridad corporal, prevención de violencias, sexualidad, reproducción, anticoncepción e infecciones de transmisión sexual. Se recuerda el derecho a decidir, a recibir atención sin discriminación, a la intimidad y a acceder oportunamente a servicios de salud sexual y reproductiva.')]:[]),
  sectionTitle('RECOMENDACIONES PARA SALUD VISUAL'),
  p(early?(months!==null&&months<36?'Observar fijación y seguimiento visual, respuesta a rostros y alineación ocular. Evitar pantallas, favorecer luz natural sin exposición solar directa y consultar ante ausencia de fijación, desviación ocular persistente, pupila blanca, lagrimeo o enrojecimiento.':'Realizar tamizaje visual desde los 3 años con optotipos infantiles (LEA o figuras de Kramer) según disponibilidad. Si no coopera o se detecta alteración, remitir para valoración visual. Favorecer actividades al aire libre, buena iluminación y uso limitado de pantallas.'):'Favorecer actividades al aire libre con protección adecuada, mantener buena iluminación durante las actividades de lectura y estudio, procurar un ambiente oscuro y tranquilo para dormir y evitar la exposición prolongada a pantallas. Consultar si presenta dificultad para ver, acercamiento excesivo a objetos, dolor ocular, cefalea frecuente o desviación de los ojos.'),
  sectionTitle('RECOMENDACIONES PARA SALUD AUDITIVA'),
  p('Evitar la exposición a ruidos intensos y el uso de audífonos a volumen elevado. No introducir copitos, bastoncillos ni otros objetos en los oídos. Secar únicamente la parte externa después del baño y consultar ante dolor, secreción, zumbidos o disminución de la audición.'),
  sectionTitle('SIGNOS DE ALARMA'),
  p(adolescent?'Consultar de inmediato por dolor de cabeza intenso, dolor en el tórax, fiebre alta persistente, dificultad respiratoria, pérdida de la conciencia, convulsiones, sangrado, dolor intenso o deterioro rápido del estado general. Consultar también ante ánimo triste persistente, pérdida de interés, ideas de muerte o suicidio, autolesiones, irritabilidad incontrolable, consumo problemático de sustancias, signos de abuso o maltrato, o cambios importantes del comportamiento y rendimiento escolar.':early?'Consultar de inmediato si no puede comer, beber o lactar; vomita todo; presenta fiebre, respiración rápida o dificultad respiratoria, palidez o coloración morada, diarrea con sangre, irritabilidad inconsolable, somnolencia marcada, convulsiones, deshidratación o deterioro rápido. Consultar también ante sospecha de maltrato, abuso o pérdida de habilidades adquiridas.':'Consultar de inmediato por urgencias si el menor no puede comer o beber, vomita todo, presenta fiebre persistente, dificultad o rapidez respiratoria, coloración pálida o morada, diarrea con sangre, convulsiones, somnolencia marcada, sangrado, dolor intenso o cambios importantes del comportamiento. También se debe consultar ante signos de maltrato, abuso, ánimo triste persistente, irritabilidad incontrolable o dificultades escolares de aparición reciente.'),
  sectionTitle('PLAN'),
  narrative('Desparasitación','Se envía desparasitante de acuerdo con la valoración médica, la edad, el peso y el protocolo institucional.'),
  narrative('Crecimiento, desarrollo y vacunación','Brindo educación sobre la importancia del uso del carné de crecimiento y desarrollo y de mantener al día el esquema de vacunación.'),
  narrative('Alimentación saludable','Se orienta a ofrecer alimentos naturales y variados acordes con la edad, evitando azúcar, exceso de sal y alimentos ultraprocesados, con horarios regulares y porciones adecuadas.'),
  narrative('Crianza y prevención de accidentes','Brindo recomendaciones sobre pautas de crianza, medidas de buen trato, establecimiento de límites, restricción del uso de pantallas y prevención de accidentes en el hogar.'),
  narrative('Prevención del uso de pólvora','Se orienta sobre la importancia del no uso de pólvora en menores. Su manipulación puede ocasionar quemaduras graves, lesiones físicas, amputaciones y otros eventos que ponen en riesgo la vida. Se recomienda evitar su uso, promover celebraciones seguras y mantener vigilancia constante de los menores.'),
  ...(early?[narrative('Suplementación','Se valora y envía suplementación con vitamina A, hierro u otros micronutrientes de acuerdo con la edad, el peso, los antecedentes, la valoración clínica y el protocolo institucional.'),narrative('Desarrollo y crianza',months!==null&&months<12?'Se promueve lactancia materna, estimulación temprana, sueño seguro, vínculo afectivo y reconocimiento de los hitos del desarrollo.':'Se promueven juego, lectura, lenguaje, autonomía progresiva, higiene oral, buen trato, límites consistentes y reconocimiento oportuno de alteraciones del desarrollo.'),narrative('Seguimiento',months!==null&&months<12?'Control de crecimiento y desarrollo según edad y ruta institucional; en lactantes, el intervalo se individualiza y puede ser cercano a dos meses.':'Control de crecimiento y desarrollo según edad y ruta institucional; para lactante mayor y preescolar se considera seguimiento semestral.')]:[]),
  ...(adolescent?[narrative('Salud oral','Se envía a higiene oral u odontología según hallazgos y ruta institucional.'),narrative('Tamizajes','Se consideran tamizajes para anemia, salud mental, consumo de alcohol u otras sustancias e ITS/ETS de acuerdo con sexo, edad, antecedentes, riesgos identificados y protocolo institucional.'),narrative('Seguimiento','Se programa control de adolescencia de acuerdo con la edad y la ruta institucional.')]:[]),
  new Paragraph({children:[text('Nota: ',true,NAVY,16),text('Los indicadores antropométricos son herramientas de apoyo y deben interpretarse junto con la valoración clínica integral.',false,TEXT,16)],spacing:{before:160,after:80}})
 ];
 return new Document({creator:'SIVE',title:documentTitle,description:'Historia clínica generada por la PWA SIVE',styles:{default:{document:{run:{font:'Arial',size:18,color:TEXT},paragraph:{spacing:{after:60,line:240}}}}},sections:[{properties:{page:{size:{width:12240,height:15840},margin:{top:1220,right:1440,bottom:1120,left:1440},header:500,footer:500}},headers:{default:new Header({children:[headerTable,new Paragraph({border:{bottom:{style:BorderStyle.SINGLE,size:12,color:TEAL}},spacing:{after:80}})]})},footers:{default:new Footer({children:[new Paragraph({children:[text('SIVE · Documento generado digitalmente · Página ',false,TEAL,15),new TextRun({children:[PageNumber.CURRENT],font:'Arial',size:15,color:TEAL})],alignment:AlignmentType.CENTER})]})},children}]});
}

export async function createClinicalDocx(data,who){const D=globalThis.docx;if(!D)throw new Error('Generador DOCX no disponible');const logoResponse=await fetch('./logo-sive.jpeg');if(!logoResponse.ok)throw new Error('No se pudo cargar el logo SIVE');const logo=new Uint8Array(await logoResponse.arrayBuffer()),doc=buildClinicalDocument(D,data,who,logo),blob=await D.Packer.toBlob(doc),category=data.cycle==='early'?'Primera-Infancia':data.cycle==='adolescent'?'Adolescencia':'Infancia',patient=(data.name||'paciente').replace(/[^a-z0-9áéíóúñ]+/gi,'-').replace(/^-+|-+$/g,'');return{blob,fileName:`SIVE-Historia-${category}-${patient}.docx`}}
export async function downloadClinicalDocx(data,who){const{blob,fileName}=await createClinicalDocx(data,who),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=fileName;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);return{blob,fileName}}
