import { WHO_DATA } from './who-data.js';

const tableCache=new Map();
function rows(name){if(tableCache.has(name))return tableCache.get(name);const t=WHO_DATA[name],mapped=t.rows.map(r=>Object.fromEntries(t.columns.map((c,i)=>[c,r[i]])));tableCache.set(name,mapped);return mapped}
const number=v=>{const n=Number(v);return Number.isFinite(n)&&n>0?n:null};
const sexCode=v=>v==='Masculino'?1:v==='Femenino'?2:null;
const dateDays=(a,b)=>{if(!a||!b)return null;const x=new Date(`${a}T12:00:00Z`),y=new Date(`${b}T12:00:00Z`);const d=(y-x)/86400000;return Number.isFinite(d)&&d>=0?d:null};
function lms(y,{l,m,s},adjusted=true){if(!y||!m||!s)return null;let z=l===0?Math.log(y/m)/s:(Math.pow(y/m,l)-1)/(s*l);if(adjusted&&Math.abs(z)>3){const val=sd=>m*Math.pow(1+l*s*sd,1/l),p3=val(3),n3=val(-3),p23=p3-val(2),n23=val(-2)-n3;if(z>3)z=3+(y-p3)/p23;else z=-3+(y-n3)/n23}return z}
function exactAgeLms(name,sex,age){const all=rows(name).filter(r=>r.sex===sex);if(name.endsWith('5')){const lo=Math.trunc(age),hi=Math.trunc(age+1),f=age-lo,a=all.find(r=>r.age===lo),b=all.find(r=>r.age===hi)||a;if(!a)return null;return {l:a.l+f*(b.l-a.l),m:a.m+f*(b.m-a.m),s:a.s+f*(b.s-a.s)}}return all.find(r=>r.age===Math.round(age))||null}
function sizeLms(name,sex,size){const all=rows(name).filter(r=>r.sex===sex),key=name==='wfl'?'length':'height',lo=Math.trunc(size*10)/10,hi=Math.trunc(size*10+1)/10,f=(size-lo)/.1,a=all.find(r=>Math.abs(r[key]-lo)<.001),b=all.find(r=>Math.abs(r[key]-hi)<.001)||a;if(!a)return null;return {l:a.l+f*(b.l-a.l),m:a.m+f*(b.m-a.m),s:a.s+f*(b.s-a.s)}}
function erf(x){const sign=x<0?-1:1,a=Math.abs(x),t=1/(1+.3275911*a),y=1-(((((1.061405429*t-1.453152027)*t)+1.421413741)*t-.284496736)*t+.254829592)*t*Math.exp(-a*a);return sign*y}
const percentile=z=>Math.max(0.1,Math.min(99.9,50*(1+erf(z/Math.SQRT2))));
function classify(code,z,older){if(code==='bfa'||code==='wfl'){if(z<-3)return'Delgadez severa';if(z<-2)return'Delgadez';if(z>3)return'Obesidad';if(z>2)return'Sobrepeso';if(!older&&z>1)return'Riesgo de sobrepeso';return'Adecuado'}if(code==='hfa'){if(z<-3)return'Talla baja severa';if(z<-2)return'Talla baja';return'Talla adecuada'}if(code==='wfa'){if(z<-3)return'Peso bajo severo';if(z<-2)return'Peso bajo';return'Peso para la edad adecuado'}if(code==='hcfa'||code==='acfa'){if(z<-2)return'Por debajo de −2 DE';if(z>2)return'Por encima de +2 DE';return'Dentro de ±2 DE'}return'Sin clasificación'}
const flags={hfa:[-6,6],wfa:[-6,5],bfa:[-5,5],wfl:[-5,5],hcfa:[-5,5],acfa:[-5,5]};
function add(out,code,label,z,older){if(z==null||!Number.isFinite(z))return;const [min,max]=flags[code],flag=z<min||z>max;out.push({code,label,z:Math.round(z*100)/100,percentile:Math.round(percentile(z)*10)/10,classification:classify(code,z,older),flag})}
export function calculateWho(data){const sex=sexCode(data.sex),weight=number(data.weight),rawHeight=number(data.height),head=number(data.headCircumference),arm=number(data.armCircumference),days=dateDays(data.birthDate,data.visitDate||new Date().toISOString().slice(0,10));if(!sex||days==null||!weight||!rawHeight)return {results:[],error:'Completa sexo, fechas, peso y talla para calcular.'};const months=days/30.4375,older=months>=60,out=[];if(!older){if(months>=60)return {results:[],error:'La edad está fuera del estándar seleccionado.'};const position=data.measurementPosition|| (days<731?'Recumbente':'De pie');let height=rawHeight;if(days<731&&position==='De pie')height+=.7;if(days>=731&&position==='Recumbente')height-=.7;const bmi=weight/Math.pow(height/100,2),oedema=data.oedema==='Sí';add(out,'hfa','Longitud/talla para la edad',lms(height,exactAgeLms('hfa0',sex,days),false),false);if(!oedema){add(out,'wfa','Peso para la edad',lms(weight,exactAgeLms('wfa0',sex,days)),false);add(out,'bfa','IMC para la edad',lms(bmi,exactAgeLms('bfa0',sex,days)),false);const metric=days<731?'wfl':'wfh';add(out,'wfl',days<731?'Peso para la longitud':'Peso para la talla',lms(weight,sizeLms(metric,sex,height)),false)}if(head)add(out,'hcfa','Perímetro cefálico para la edad',lms(head,exactAgeLms('hcfa',sex,days)),false);if(arm&&days>=91)add(out,'acfa','Perímetro braquial para la edad',lms(arm,exactAgeLms('acfa',sex,days)),false);return {results:out,bmi,ageMonths:months,standard:'Estándares OMS 2006/2007 (0–5 años)'}}const bmi=weight/Math.pow(rawHeight/100,2),oedema=data.oedema==='Sí';add(out,'hfa','Talla para la edad',lms(rawHeight,exactAgeLms('hfa5',sex,months),false),true);if(!oedema){add(out,'bfa','IMC para la edad',lms(bmi,exactAgeLms('bfa5',sex,months)),true);if(months<=120)add(out,'wfa','Peso para la edad',lms(weight,exactAgeLms('wfa5',sex,months)),true)}return {results:out,bmi,ageMonths:months,standard:'Referencia OMS 2007 (5–19 años)'}}
function resultColor(r){if(r.flag)return'#7f1d1d';if(r.z<-2||r.z>2)return'#dc2626';if(r.z<-1||r.z>1)return'#d97706';return'#15803d'}
function scaleSvg(r){const x=Math.max(5,Math.min(295,150+r.z*42));return `<svg class="z-scale" viewBox="0 0 300 54" role="img" aria-label="${r.label}: Z ${r.z}"><rect x="5" y="17" width="46" height="14" rx="7" fill="#fecaca"/><rect x="51" y="17" width="56" height="14" fill="#fed7aa"/><rect x="107" y="17" width="86" height="14" fill="#bbf7d0"/><rect x="193" y="17" width="56" height="14" fill="#fed7aa"/><rect x="249" y="17" width="46" height="14" rx="7" fill="#fecaca"/><path d="M${x} 8l7 8h-14z" fill="#082f52"/><line x1="${x}" y1="16" x2="${x}" y2="36" stroke="#082f52" stroke-width="3"/><g fill="#607773" font-size="9"><text x="4" y="48">−3</text><text x="98" y="48">−1</text><text x="147" y="48">0</text><text x="238" y="48">+2</text><text x="284" y="48">+3</text></g></svg>`}
export function renderWhoResults(data){const calc=calculateWho(data);if(calc.error)return `<section class="form-card results-card"><div class="section-title"><h2>Resultados antropométricos OMS</h2><p>${calc.error}</p></div></section>`;return `<section class="form-card results-card"><div class="section-title"><h2>Resultados antropométricos OMS</h2><p>${calc.standard}. Edad exacta: ${calc.ageMonths.toFixed(1)} meses · IMC: ${calc.bmi.toFixed(2)} kg/m².</p></div><div class="results-grid">${calc.results.map(r=>`<article class="z-result ${r.flag?'flagged':''}"><div><h3>${r.label}</h3><span class="result-class">${r.flag?'Valor implausible: verificar medición':r.classification}</span></div><div class="result-numbers"><span><small>Percentil</small><strong>${r.percentile}</strong></span><span style="--result-color:${resultColor(r)}"><small>Z-score</small><strong>${r.z.toFixed(2)}</strong></span></div>${scaleSvg(r)}</article>`).join('')}</div><p class="results-note">Herramienta de apoyo basada en referencias OMS. No sustituye valoración, diagnóstico ni juicio clínico.</p></section>`}
